apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alt3rius/ibdb-wsb.git
    targetRevision: HEAD
    path: manifests/istio-resources
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true