apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  namespace: webapp
spec:
  template:
    spec:
      containers:
      - name: migration
        image: alterius/ibdb
        command:
        - bash
        - -c
        - "flask db init && flask db migrate && flask db upgrade"
        envFrom:
        - configMapRef:
            name: db-cm
      restartPolicy: Never


  backoffLimit: 4

