apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- install.yaml

patchesStrategicMerge:
- patches/configmap-patch.yaml
- patches/add-custom-kustomize.yaml
- patches/disable-tls.yaml
